### ISSUE TITLE
Future of this Repo

### ISSUE THREAD

**Issue by Craytor** [AlexNeises/nexrad.js#3]
Will there be continued development of this repo in the future?

**Comment by AlexNeises** [comment]
Actually, yes. I've got some progress I need to push. At the moment, the processing is going to be done in Python since the decoders are already available and more accurate. What I'm doing on the JavaScript side is combining these radar mosaics onto a Google Maps overlay.  I'll push everything I currently have into a new branch called feature/google-maps.

**Comment by Craytor** [comment]
Okay, that sounds intriguing. Will python be converting them to images, or will JavaScript display the radar data as the example currently is (not by images)?

**Comment by AlexNeises** [comment]
That's where I was running into issues. I can continue work on processing them the way I am now via JavaScript, or I can go the Python route which is generating tile images based on the Google Maps zoom level.

**Comment by AlexNeises** [comment]
The problem with the JS generation is how slow it can be. A powerful computer can process everything with little issue, but a standard off-the-shelf computer will work pretty hard to process the data. That's why I'm experimenting with the Python tiles.

**Comment by Craytor** [comment]
Okay, I see. I noticed on my end that the map was seemed "laggy" (if that makes sense) when zooming in and out and re-positioning the app with the current example. 

I'd actually be willing to see both.

I kind of eventually want to figure out how it works now as I think it could be beneficial, as it could ensure higher res imagery if that makes sense?

**Comment by Craytor** [comment]
> The problem with the JS generation is how slow it can be. 

I think that is in regards to the "laggyness" I felt?

**Comment by AlexNeises** [comment]
Yup. The laggyness is a new svg being drawn for each "pixel" the radar is showing. I don't remember off the top of my head, but there's somewhere in the range of 30K different svg objects being drawn. I'm not very good at svg generation in general, but if you want to take a stab at it, be my guest!

**Comment by AlexNeises** [comment]
Also, the Google Maps branch has been pushed.

**Comment by Craytor** [comment]
Alright, interesting. I'm not too sure about SVG either, but could look into it in the future. Just checked out  the branch, and it seems really good.

Also, the NOQ titles on the Google Maps (as compared to the original map) seem like the lighter returns are not being displayed. Additionally, which python scripts are you using to process the radar data?

Thanks!

**Comment by AlexNeises** [comment]
I pushed a script I threw together to generate the tiles in a format that Google Maps likes. You'll need to install PyART.  `pip install pyart` should install it fine.

**Comment by AlexNeises** [comment]
I will be moving all future commits into the Nexview organization.

https://github.com/Nexview

**Comment by Craytor** [comment]
Okay, thank you for letting me know. I'll try and help out where I can.

**Comment by Craytor** [comment]
Also, @AlexNeises any chance you would want to create a Slack team?

**Comment by AlexNeises** [comment]
I can do that.

**Comment by AlexNeises** [comment]
https://join.slack.com/nexview/shared_invite/MTkzMDU1OTYxOTA3LTE0OTY3MTYzMDktZDNmMTc4MTc5OQ
